// vega.web.react/src/App/Navigation.js
import React from 'react';
import {NavLink} from 'react-router-dom';

const Navigation = () => {
   return(
    <div>
        <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <ul className="navbar-nav">
                <li className='nav-item'>
                    <NavLink className="nav-link" activeClassName='activeNavLink' to="/">List Vehicles</NavLink>
                </li>
                <li className='nav-item'>
                    <NavLink className="nav-link" activeClassName='activeNavLink' to="/vehicles/new">New Vehicle</NavLink>
                </li>
            </ul>
        </nav>
        <div className='mb-4' />
    </div>
    );
}

export default Navigation;

// Vega.Web.Angular/src/app/navigation/navigation.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-navigation',
    templateUrl: './navigation.component.html'
})
export class NavigationComponent {

}

<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" [routerLink]="['/']">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown">
                        Vehicle
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" [routerLink]="['vehicles/new']">New Vehicle</a>
                        <a class="dropdown-item" [routerLink]="['vehicles']">List Vehicles</a>
                    </div>
                </li>              
            </ul>
        </div>
    </nav>
</div>
